### ISSUE TITLE
[Question] Module Verification

### ISSUE THREAD

**Issue by klesher** [terraform-aws-modules/terraform-aws-cloudwatch#3]
Hello,

I was looking for an existing CloudWatch module from `terraform-aws-modules` as I have had great results with your other modules, but noticed that this one is not _Verified_ in the Terraform Registry.  Terraform's [criteria for verified modules](https://www.terraform.io/docs/registry/modules/verified.html) does note that unverified modules may still be of high quality, as I would agree is the case with this one from digging through the code and use of some of your other verified modules.  

I will likely use this module regardless, but I was curious if you're aware of why this module isn't verified but a number of your others have been?    Module verification is supposedly expanding per the previous link, but the [GitHub source for that page](https://github.com/hashicorp/terraform/blob/master/website/docs/registry/modules/verified.html.md) hasn't been updated since Sep 15, 2017, so unsure what movement has been made with that from the HashiCorp side since then.  Is there anything you're aware of that could help with this process for this and your other currently unverified modules?  

Thanks for all of the great contributions to Terraform!  Much appreciated!

**Comment by antonbabenko** [comment]
Hi Kevin,

Thanks for the support, first of all!

I know that it is hard to figure out the reasons for partial acceptance of Terraform AWS modules as verified, and I don't know many details either.

All the `terraform-aws-modules` are listed here - https://registry.terraform.io/modules/terraform-aws-modules . Most of them are matching to Terraform's [criterias for verified modules](https://www.terraform.io/docs/registry/modules/verified.html) already.

I hope to know more about this in the near future myself so that I can give a more complete answer.

Closing this issue for now.
